# Generated by Django 5.0.6 on 2024-05-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
