# Generated by Django 5.0.6 on 2024-05-29 07:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_experience_tags_alter_userprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='experience',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章標題')),
                ('description', models.TextField(verbose_name='旅遊經驗')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='旅遊日期')),
                ('tags', models.ManyToManyField(related_name='post', to='travel.tag', verbose_name='標籤')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='發文者')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travel.post', verbose_name='文章'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
