# Generated by Django 5.0.6 on 2024-05-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_userprofile_member_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='member_id',
            field=models.CharField(blank=True, help_text='系統將自動生成十碼會員編號', max_length=10, unique=True, verbose_name='會員編號'),
        ),
    ]
