# Generated by Django 5.0.6 on 2024-06-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_remove_photo_experience_post_photo_post_and_more'),
        ('travel', '0010_rename_profile_picture_userprofile_picture'),
    ]

    operations = [
    ]
