# Generated by Django 5.0.6 on 2024-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_rename_photo_post_photo_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, help_text='請上傳1:1圖片', null=True, upload_to='profile_pictures/', verbose_name='用戶頭像'),
        ),
    ]
