# Generated by Django 5.0.6 on 2024-06-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default="{% static 'picture/defult_head.png' %}", help_text='請上傳1:1圖片', null=True, upload_to='profile_pictures/', verbose_name='用戶頭像'),
        ),
    ]
