# Generated by Django 5.0.4 on 2024-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Post_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ManyToManyField(related_name='posts', to='travel.picture', verbose_name='內文圖片'),
        ),
    ]
