# Generated by Django 5.0.6 on 2024-06-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_picture_post_pictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_Photo',
        ),
    ]
