# Generated by Django 5.0.6 on 2024-06-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_delete_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
