# Generated by Django 5.0.6 on 2024-06-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, verbose_name='文章標題'),
        ),
    ]
