# Generated by Django 4.2.11 on 2024-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='Post_photos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='posts', to='travel.picture', verbose_name='內文圖片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='travel.tag', verbose_name='標籤'),
        ),
    ]
